name = "SparseDirectSolver"
uuid = "dc8e0fd9-41f1-440b-9624-22817132f700"
version = "0.1.0"
authors = ["Michel Schanen <Michel.Schanen@gmail.com>"]

[deps]
AMD = "14f7f29c-3bd6-536c-9a0b-7339e30b5a3e"
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
Atomix = "a9b6321e-bd34-4604-b9c9-b65b8de01458"
CliqueTrees = "60701a23-6482-424a-84db-faee86b9b1f8"
GPUArrays = "0c68f7d7-f131-5f86-a1c3-88cf8149b2d7"
GPUArraysCore = "46192b85-c4d5-4398-a991-12ede77f4527"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[weakdeps]
AMDGPU = "21141c5a-9bdb-4563-92ae-f87d6854732e"
CUDACore = "bd0ed864-bdfe-4181-a5ed-ce625a5fdea2"
Krylov = "ba0b0d4f-ebba-5204-a429-3ac8c609bfb7"
Metis = "2679e427-3c69-5b7f-982b-ece356f1e94b"
cuBLAS = "182d3088-87b7-4494-8cad-fc6afaa545bc"
cuSOLVER = "887afef0-6a32-4de5-add4-7827692ba8fc"
cuSPARSE = "b26da814-b3bc-49ef-b0ee-c816305aa060"

[extensions]
SparseDirectSolverAMDGPUExt = "AMDGPU"
SparseDirectSolverCUDAExt = ["CUDACore", "cuBLAS", "cuSOLVER", "cuSPARSE"]
SparseDirectSolverKrylovExt = "Krylov"
SparseDirectSolverMetisExt = "Metis"

[compat]
AMD = "0.5"
AMDGPU = "2"
Adapt = "4"
Atomix = "1"
CUDACore = "6"
CliqueTrees = "1"
GPUArrays = "11, 12"
GPUArraysCore = "0.2"
KernelAbstractions = "0.9"
Krylov = "0.10"
LinearAlgebra = "1.13"
Metis = "1"
SparseArrays = "1.13"
cuBLAS = "6"
cuSOLVER = "6"
cuSPARSE = "6"
julia = "1.13"
