# Renders the cuDSS vs SparseDirectSolver.jl comparison from the CSVs written by
# `compare.jl`: `bench/comparison/comparison.md` (overview of every planned
# feature, then one table per feature) and `bench/comparison/comparison.png`
# (geometric-mean time ratio SDS/cuDSS per feature and phase).
#
#   julia --project=bench/report bench/compare_report.jl [--no-plot]
#
# Features whose task is not done in TASKS.md are listed with blank SDS cells.

module BenchCompareReport

using DelimitedFiles
using Printf

include(joinpath(@__DIR__, "features.jl"))
using .BenchFeatures

export read_rows, ratio_summary, render_markdown, PHASES

const PHASES = ("analysis", "factorization", "refactorization", "solve")
const DIR = joinpath(@__DIR__, "comparison")

"""
    read_rows(path) -> Vector{Dict{String,String}}

Rows of a CSV written by `compare.jl`, keyed by column name; empty if the file does not exist.
"""
function read_rows(path::AbstractString)
    isfile(path) || return Dict{String, String}[]
    data, header = readdlm(path, ',', String; header = true, quotes = false)
    return [Dict(zip(vec(header), data[i, :])) for i in axes(data, 1)]
end

ok(r) = r !== nothing && r["status"] == "ok"
seconds(r, p) = parse(Float64, r["$(p)_s"])
find_row(rows, f, m) = (i = findfirst(r -> r["feature"] == f.id && r["matrix"] == m, rows); i === nothing ? nothing : rows[i])

"""
    matrices_of(f, cudss_rows, sds_rows) -> Vector{String}

Matrix names with a row for feature `f` on either side, cuDSS order first.
"""
matrices_of(f, cudss_rows, sds_rows) =
    unique!([r["matrix"] for r in vcat(cudss_rows, sds_rows) if r["feature"] == f.id])

"""
    ratio_summary(f, cudss_rows, sds_rows) -> (ratios, count)

Geometric mean of the SDS/cuDSS time ratio per phase over the matrices where
both rows are `ok` (`nothing` per phase when there is none), and their number.
"""
function ratio_summary(f, cudss_rows, sds_rows)
    pairs = [(find_row(cudss_rows, f, m), find_row(sds_rows, f, m)) for m in matrices_of(f, cudss_rows, sds_rows)]
    filter!(((c, s),) -> ok(c) && ok(s), pairs)
    isempty(pairs) && return Dict{String, Union{Nothing, Float64}}(p => nothing for p in PHASES), 0
    gm(p) = exp(sum(log(seconds(s, p) / seconds(c, p)) for (c, s) in pairs) / length(pairs))
    return Dict{String, Union{Nothing, Float64}}(p => gm(p) for p in PHASES), length(pairs)
end

fmt_ms(r, p) = ok(r) ? @sprintf("%.3g", seconds(r, p) * 1e3) : r === nothing ? "" : "fail"
fmt_ratio(x) = x === nothing ? "" : @sprintf("%.2f×", x)
fmt_ratio(c, s, p) = ok(c) && ok(s) ? fmt_ratio(seconds(s, p) / seconds(c, p)) : ""
fmt_field(r, k) = ok(r) && !isempty(r[k]) ? @sprintf("%.3g", parse(Float64, r[k])) : ""

state(f, implemented) = implemented ? "done" : "pending"

"""
    render_markdown(io, cudss_rows, sds_rows; features = COMPARE_FEATURES, implemented = feature_implemented)

Writes the comparison as Markdown: an overview with one line per feature, then
per feature a table with cuDSS ms, SDS ms and the ratio for each phase, nnz(L)
and the relative residual of both solvers. Cells without a row stay blank, a
failed row shows `fail` and its message below the table.
"""
function render_markdown(io::IO, cudss_rows, sds_rows; features = COMPARE_FEATURES,
                         implemented = feature_implemented, plot = true)
    println(io, "# cuDSS vs SparseDirectSolver.jl\n")
    println(io, "Generated by `bench/compare_report.jl` from `bench/comparison/{cudss,sds}.csv` ",
            "(`bench/compare.jl`). Times are BenchmarkTools medians per phase on a fresh solver; ",
            "the ratio is SDS time / cuDSS time, so below 1 means SparseDirectSolver.jl is faster. ",
            "Features whose task is not done in TASKS.md have blank SDS cells.\n")
    plot && println(io, "![SDS/cuDSS time ratio per feature](comparison.png)\n")
    println(io, "## Overview\n")
    println(io, "Geometric mean of the SDS/cuDSS ratio over the matrices both solvers ran.\n")
    println(io, "| feature | task | status | matrices | analysis | factorization | refactorization | solve |")
    println(io, "| --- | --- | --- | --- | --- | --- | --- | --- |")
    for f in features
        ratios, count = ratio_summary(f, cudss_rows, sds_rows)
        println(io, "| ", f.title, " | ", f.task, " | ", state(f, implemented(f)), " | ", count == 0 ? "" : count,
                " | ", join((fmt_ratio(ratios[p]) for p in PHASES), " | "), " |")
    end
    println(io)
    for f in features
        println(io, "## ", f.title, "\n")
        println(io, "`", f.id, "`, ", f.task, " (", state(f, implemented(f)), "), structure `", f.structure, "`, ",
                f.T, ", nrhs = ", f.nrhs, f.kind == :ubatch ? ", uniform batch of $(f.nbatch)" : "",
                f.cudss_supported ? "" : ", no cuDSS counterpart", ".\n")
        names = matrices_of(f, cudss_rows, sds_rows)
        if isempty(names)
            println(io, "Not run yet.\n")
            continue
        end
        print(io, "| matrix | n |")
        foreach(p -> print(io, " $p cuDSS ms | SDS ms | ratio |"), PHASES)
        println(io, " nnz(L) cuDSS | SDS | relres cuDSS | SDS |")
        println(io, "|", repeat(" --- |", 2 + 3 * length(PHASES) + 4))
        failures = String[]
        for m in names
            c, s = find_row(cudss_rows, f, m), find_row(sds_rows, f, m)
            n = c !== nothing ? c["n"] : s["n"]
            print(io, "| ", m, " | ", n, " |")
            foreach(p -> print(io, " ", fmt_ms(c, p), " | ", fmt_ms(s, p), " | ", fmt_ratio(c, s, p), " |"), PHASES)
            println(io, " ", fmt_field(c, "lu_nnz"), " | ", fmt_field(s, "lu_nnz"), " | ", fmt_field(c, "relres"),
                    " | ", fmt_field(s, "relres"), " |")
            for (who, r) in (("cuDSS", c), ("SDS", s))
                r !== nothing && !ok(r) && push!(failures, "$who on $m: $(r["status"])")
            end
        end
        println(io)
        isempty(failures) || (foreach(x -> println(io, "* ", x), failures); println(io))
    end
    println(io, "## Runs\n")
    for (who, rows) in (("cuDSS", cudss_rows), ("SparseDirectSolver.jl", sds_rows))
        isempty(rows) && (println(io, "* ", who, ": no results."); continue)
        runs = unique((r["device"], r["version"], r["git_sha"], r["date"]) for r in rows)
        for (d, v, g, t) in runs
            println(io, "* ", who, " ", v, " on ", d, ", repository ", isempty(g) ? "?" : g, ", ", t, ".")
        end
    end
end

end # module BenchCompareReport

using .BenchCompareReport

const MAKE_PLOT = abspath(PROGRAM_FILE) == (@__FILE__) && !("--no-plot" in ARGS)
if MAKE_PLOT
    using CairoMakie
end

"""
    write_plot(path, cudss_rows, sds_rows)

Grouped bars of the geometric-mean SDS/cuDSS ratio per feature and phase, log
scale, bars drawn from 1; features without results keep an empty slot.
"""
function write_plot(path, cudss_rows, sds_rows)
    F = BenchCompareReport.BenchFeatures
    feats = F.COMPARE_FEATURES
    xs, ys, groups = Int[], Float64[], Int[]
    for (i, f) in enumerate(feats), (j, p) in enumerate(PHASES)
        r = first(ratio_summary(f, cudss_rows, sds_rows))[p]
        r === nothing || (push!(xs, i); push!(ys, r); push!(groups, j))
    end
    labels = [F.feature_implemented(f) ? "$(f.id) ($(f.task))" : "$(f.id) ($(f.task), pending)" for f in feats]
    fig = Figure(size = (1200, 560))
    ax = Axis(fig[1, 1]; yscale = log10, xticks = (1:length(feats), labels), xticklabelrotation = π / 4,
              ylabel = "SDS time / cuDSS time (geometric mean)",
              yticks = [0.01, 0.02, 0.05, 0.1, 0.2, 0.5, 1, 2, 5, 10, 20, 50, 100],
              ytickformat = vs -> ["$(round(v; sigdigits = 2))×" for v in vs],
              title = "SparseDirectSolver.jl vs cuDSS: below 1 is faster")
    colors = Makie.wong_colors()[1:length(PHASES)]
    isempty(xs) || barplot!(ax, xs, ys; dodge = groups, n_dodge = length(PHASES), width = 0.8,
                            color = colors[groups], fillto = 1.0)
    hlines!(ax, [1.0]; color = :black, linestyle = :dash)
    xlims!(ax, 0.5, length(feats) + 0.5)
    lo, hi = isempty(ys) ? (1.0, 1.0) : extrema(ys)
    ylims!(ax, min(lo, 1.0) / 1.5, max(hi, 1.0) * 1.5)
    Legend(fig[1, 2], [PolyElement(color = c) for c in colors], collect(PHASES), "phase")
    save(path, fig)
    return path
end

function main()
    dir = BenchCompareReport.DIR
    cudss_rows = read_rows(joinpath(dir, "cudss.csv"))
    sds_rows = read_rows(joinpath(dir, "sds.csv"))
    md = joinpath(dir, "comparison.md")
    plot = MAKE_PLOT || isfile(joinpath(dir, "comparison.png"))
    open(io -> render_markdown(io, cudss_rows, sds_rows; plot), md, "w")
    println("wrote ", md)
    MAKE_PLOT && println("wrote ", Base.invokelatest(write_plot, joinpath(dir, "comparison.png"), cudss_rows, sds_rows))
end

if abspath(PROGRAM_FILE) == @__FILE__
    main()
end
