# Build the documentation: julia --project=docs -e 'using Pkg; Pkg.instantiate()'
#                          julia --project=docs docs/make.jl
# The examples run on the KernelAbstractions CPU backend and on CUDA (the docs
# are built on the self-hosted `cuda` runner, see .github/workflows/Documentation.yml).

using Documenter
using LinearAlgebra
using SparseArrays
using SparseDirectSolver
using CUDA

CUDA.functional() || error("the documentation examples need a functional CUDA.jl")
CUDA.versioninfo()

const CUDAExt = Base.get_extension(SparseDirectSolver, :SparseDirectSolverCUDAExt)

# the cuDSS comparison plot is regenerated by hand in bench/ (bench/README.md)
cp(joinpath(@__DIR__, "..", "bench", "comparison", "comparison.png"),
   joinpath(@__DIR__, "src", "assets", "comparison.png"); force = true)

DocMeta.setdocmeta!(SparseDirectSolver, :DocTestSetup, :(using SparseDirectSolver); recursive = true)

makedocs(
    sitename = "SparseDirectSolver.jl",
    authors = "Michel Schanen and contributors",
    format = Documenter.HTML(
        prettyurls = get(ENV, "CI", nothing) == "true",
        canonical = "https://exanauts.github.io/SparseDirectSolver.jl/stable/",
        mathengine = Documenter.KaTeX(),
        # the internals page holds every docstring of the package
        size_threshold = 1024 * 1024,
        size_threshold_warn = 512 * 1024,
    ),
    modules = [SparseDirectSolver, CUDAExt],
    repo = Remotes.GitHub("exanauts", "SparseDirectSolver.jl"),
    checkdocs = :exports,
    pages = [
        "Home" => "index.md",
        "Quick start" => "quickstart.md",
        "Manual" => [
            "Phases" => "man/phases.md",
            "Parameters" => "man/parameters.md",
            "Symmetric indefinite systems" => "man/indefinite.md",
            "Migrating from CUDSS.jl" => "man/cudss.md",
            "Backends" => "man/backends.md",
            "Performance" => "man/performance.md",
        ],
        "Library" => [
            "Solver" => "lib/solver.md",
            "Matrices" => "lib/matrices.md",
            "LinearAlgebra interface" => "lib/linearalgebra.md",
            "CUDA extension" => "lib/cuda.md",
            "Internals" => "lib/internals.md",
        ],
    ],
)

deploydocs(
    repo = "github.com/exanauts/SparseDirectSolver.jl.git",
    target = "build",
    devbranch = "main",
    devurl = "dev",
    push_preview = true,
)
